version: "3.5"

x-args: &default_args
  COMPOSER_VERSION: ${COMPOSER_VERSION}
  CADDY_VERSION: ${CADDY_VERSION}
  NODE_VERSION: ${NODE_VERSION}
  PHP_VERSION: ${PHP_VERSION}

services:
  server:
    build:
      context: .
      dockerfile: system/Dockerfile
      target: server_caddy
      args: *default_args
    depends_on:
      - backend
    volumes:
      - ./system/server/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./:/app
    ports:
      - "443:443"

  backend:
    build:
      context: .
      dockerfile: system/Dockerfile
      target: backend_php
      args: *default_args
    volumes:
      - ./:/app

volumes:
  caddy_data:
  caddy_config: