version: "3.5"

services:
  server:
    build:
      context: .
      dockerfile: system/Dockerfile
      target: server_caddy
    depends_on:
      - backend
    volumes:
      # - ./:/app
      - ./system/server/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    labels:
      - "traefik.http.routers.calculus.rule=Host(`calculus.anagraph.org`)"
    ports:
      - "443:443"

  backend:
    build:
      context: .
      dockerfile: system/Dockerfile
      target: backend_php

volumes:
  caddy_data:
  caddy_config:

#networks:
#  default:
#    external: true
#    name: proxy