version: "3.5"

services:
  server:
    build:
      context: .
      dockerfile: system/Dockerfile
      target: server_caddy
      args: 
        CADDY_VERSION: ${CADDY_VERSION}
        NODE_VERSION: ${NODE_VERSION}
        PHP_VERSION: ${PHP_VERSION}
        COMPOSER_VERSION: ${COMPOSER_VERSION}
    depends_on:
      - backend
    volumes:
###> Dev
      - ./:/app
###< Dev
      - ./system/server/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
###> Prod
#   labels:
#      - "traefik.http.routers.calculus.rule=Host(`calculus.anagraph.org`)"
###< Prod
###> Dev
    ports:
      - "443:443"
###< Dev

  backend:
    build:
      context: .
      dockerfile: system/Dockerfile
      target: backend_php
      args: 
        CADDY_VERSION: ${CADDY_VERSION}
        NODE_VERSION: ${NODE_VERSION}
        PHP_VERSION: ${PHP_VERSION}
        COMPOSER_VERSION: ${COMPOSER_VERSION}
###> Dev
    volumes:
      - ./:/app
###< Dev

volumes:
  caddy_data:
  caddy_config:

###> Prod
#networks:
#  default:
#    external: true
#    name: proxy
###< Prod