version: "3.5"

services:
  server:
    image: caddy:alpine
    depends_on:
      - backend
    volumes:
      - ./:/app
      - ./system/server/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    labels:
      - "traefik.http.routers.calculus.rule=Host(`calculus.anagraph.org`)"
    ports:
      - "443:443"

  backend:
    build:
      context: .
      dockerfile: system/backend/Dockerfile
      args:
        PHP_VERSION: 8
        COMPOSER_VERSION: 2
    volumes:
      - .:/app
      - ./system/backend/php-custom.ini:/usr/local/etc/php/php.ini

volumes:
  caddy_data:
  caddy_config:

#networks:
#  default:
#    external: true
#    name: proxy